properly handle open failure
Currently the failure to open itself (for reading flags from the
3P payload) causes this:
Exception: 0D, Error code: 0000
... and a write of a CW.ERR.

With this patch you'll see a somewhat cryptic
CauseWay error 04 : DOS 3.1 or better required.
... which is much better than the crash.

Fixes https://github.com/tkchia/causeway/issues/4